### PR TITLE
zh_CN.lang for 0.5.4

### PR DESCRIPTION
**Pull request by nekobuild**
update  new version of en_US.lang

### CODE REVIEW

**Comment by joshiejack** [comment]
Sorry for the trouble. One last one. There won't be anymore I promise, since I plan to release what I have on Friday. I'm going to bed now, will take a look tomorrow, will pull either way. It doesn't breakk toomuch. Plan to release on Friday.

https://github.com/PenguinSquad/Harvest-Festival/commit/d3509b2450286f686af9c6b93ed0e4dd28c6439c

**Comment by nekobuild** [comment]
never mind! Just do what you like or need to do! I‘m super fans of this mod! so I will try my best!!!

**Comment by TartaricAcid** [comment]
It's pretty good, Thank for your translation.

**Comment by GWYOG** [comment]
@YeMzZ 
Hello! I'm a fan of Harvest Moon series of games and I was intended to translate HF either. I have seen your translations. I think they're pretty good, but some translations can be improved and some typos can be fixed. 
I would like to discuss with you and help you make your translation even better. If you are willing, you can contact this QQ number: 609871947 at any time. ;-)

**Comment by 3TUSK** [comment]
Just a reminder: you don't need to left credit info in the file head - so long as your email is not changed - [git can record everything for you.](https://git-scm.com/docs/git-log)

> Seriously, I hope one day git has support for multi-author... one author and one committer is not enough sometimes...

**Pull request merged**
