### PR TITLE
Add a 12 hour clock

### PR DESCRIPTION
**Pull request by TehNut**
Disabled by default

### CODE REVIEW

**Comment by purpleposeidon** [comment]
Enabled by default pls.

**Comment by Yulife** [comment]
We Europeans use the precious 24 hour clock

**Comment by purpleposeidon** [comment]
That's cool for the Europeans, but Jenni & the rest use 12-hour time.

**Comment by joshiejack** [comment]
It's actually a mix of both because as a brit, we use both interchangeably
and different people prefer different things. And people understand both
automatically. I could change everything to be consistent but for me that
doesn't feel right. Like generally time is written using 24 but said with
12 hour. I don't see 22 as 22 but automatically see it as 10. I guess it's
different when you haven't grown up with both systems. But no matter what i
will not make a digital clock use 12 hour time as default as I find it
harder to tell the time from a glance.

**Comment by purpleposeidon** [comment]
Java probably has a locale-sensitive thingie for formatting time.

**Comment by joshiejack** [comment]
This isn't an issue i care about

**Pull request merged**
